- hosts: all
  environment:
    PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
   
  tasks:
    - name: "Copia Arquivo Dump SQL"
      copy:
        src: "dumpsql/dumpsql.sql"
        dest: "/tmp/dumpsql.sql"
   
    - name: "Alterar o acesso"
      become: yes
      shell: "mysql -u root -p\"{{ lookup('env', 'DB_PASSWORD') }}\" -e \"CREATE USER 'root'@'%' IDENTIFIED BY '{{ lookup('env', 'DB_PASSWORD') }}'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;\""
    
    - name: "Copia Dump para MySQL"
      shell: "mysql -u root -p\"{{ lookup('env', 'DB_PASSWORD') }}\" < /tmp/dumpsql.sql"