- hosts: all
  environment:
    PASSWORD: "root"
   
  tasks:
    - name: "Cria o banco de dados MySQL"
      become: yes
      mysql_db:
        name: SpringWebYoutubeTest
        login_user: "root"
        login_password: "root"
        state: present
        
    - name: "Copia Arquivo Dump SQL"
      copy:
        src: "dumpsql/dumpsql.sql"
        dest: "/tmp/dumpsql.sql"
    
    - name: "Restore database"
      mysql_db:
        name: SpringWebYoutube
        state: import
        target: /tmp/dumpsql.sql
        login_user: root
        login_password: root
        state: present

    - name: "Restarta serviço do mysql"
      become: yes
      service:
        name: mysql
        state: restarted