apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-dev
data:
  USER: root
  # PASSWORD: root
  DATABASE_URL: mysql://192.168.13.38:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
  
  # DATABASE_URL: mysql://10.111.41.255:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC # caso esteja vinculando um clusterIP na mão
